<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vmfds_pdf"
 *
 * Auto generated by Extension Builder 2013-12-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PDF Renderer',
	'description' => 'ViewHelpers for PDF rendering',
	'category' => 'plugin',
	'author' => 'Christoph Fischer',
	'author_email' => 'christoph.fischer@volksmission.de',
	'author_company' => 'Volksmission Freudenstadt',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>